// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import driver "github.com/arangodb/go-driver"
import mock "github.com/stretchr/testify/mock"

// ClientFoxx is an autogenerated mock type for the ClientFoxx type
type ClientFoxx struct {
	mock.Mock
}

// Foxx provides a mock function with given fields:
func (_m *ClientFoxx) Foxx() driver.FoxxService {
	ret := _m.Called()

	var r0 driver.FoxxService
	if rf, ok := ret.Get(0).(func() driver.FoxxService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.FoxxService)
		}
	}

	return r0
}
