// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import driver "github.com/arangodb/go-driver"
import mock "github.com/stretchr/testify/mock"

// ClientAdminBackup is an autogenerated mock type for the ClientAdminBackup type
type ClientAdminBackup struct {
	mock.Mock
}

// Backup provides a mock function with given fields:
func (_m *ClientAdminBackup) Backup() driver.ClientBackup {
	ret := _m.Called()

	var r0 driver.ClientBackup
	if rf, ok := ret.Get(0).(func() driver.ClientBackup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.ClientBackup)
		}
	}

	return r0
}
