// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import protocol "github.com/arangodb/go-driver/vst/protocol"

// vstAuthentication is an autogenerated mock type for the vstAuthentication type
type vstAuthentication struct {
	mock.Mock
}

// PrepareFunc provides a mock function with given fields: c
func (_m *vstAuthentication) PrepareFunc(c *vst.vstConnection) func(context.Context, *protocol.Connection) error {
	ret := _m.Called(c)

	var r0 func(context.Context, *protocol.Connection) error
	if rf, ok := ret.Get(0).(func(*vst.vstConnection) func(context.Context, *protocol.Connection) error); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context, *protocol.Connection) error)
		}
	}

	return r0
}
